package iwish.client;
import iwish.common.*; import iwish.common.Models.*; import javax.swing.*; import java.awt.*; import java.awt.event.*;
public class LoginFrame extends JFrame {final Color NAVY=new Color(19,30,58),PINK=new Color(239,92,125),BG=new Color(247,249,252); JTextField email=new JTextField(),name=new JTextField(); JPasswordField pass=new JPasswordField(); JLabel title=new JLabel("Welcome back"); ApiClient api; LoginFrame(){setTitle("I-Wish • Make wishes happen");setSize(920,600);setLocationRelativeTo(null);setDefaultCloseOperation(EXIT_ON_CLOSE);try{api=new ApiClient();}catch(Exception e){JOptionPane.showMessageDialog(this,"Start the server first: run ServerMain","Server unavailable",JOptionPane.ERROR_MESSAGE);} build();}
 void build(){JPanel root=new JPanel(new GridLayout(1,2)); root.setBackground(BG); JPanel hero=new JPanel(new GridBagLayout());hero.setBackground(NAVY);JLabel h=new JLabel("I-Wish");h.setForeground(Color.WHITE);h.setFont(new Font("SansSerif",Font.BOLD,48));JLabel sub=new JLabel("Small wishes. Big smiles.");sub.setForeground(new Color(190,204,231));sub.setFont(new Font("SansSerif",Font.PLAIN,18));GridBagConstraints g=new GridBagConstraints();g.gridy=0;hero.add(h,g);g.gridy=1;g.insets=new Insets(12,0,0,0);hero.add(sub,g);root.add(hero);JPanel form=new JPanel();form.setBackground(Color.WHITE);form.setBorder(BorderFactory.createEmptyBorder(55,65,55,65));form.setLayout(new BoxLayout(form,BoxLayout.Y_AXIS));title.setFont(new Font("SansSerif",Font.BOLD,30));title.setForeground(NAVY);form.add(title);JLabel hint=new JLabel("Your wish list is waiting for you.");hint.setForeground(Color.GRAY);form.add(hint);form.add(Box.createVerticalStrut(32));form.add(label("Email"));form.add(email);form.add(Box.createVerticalStrut(14));form.add(label("Password"));form.add(pass);form.add(Box.createVerticalStrut(22));JButton login=button("Sign in",PINK);form.add(login);form.add(Box.createVerticalStrut(12));JButton signup=button("Create a new account",new Color(226,231,241));signup.setForeground(NAVY);form.add(signup);login.addActionListener(e->login());signup.addActionListener(e->registerMode());root.add(form);add(root);}
 JLabel label(String s){JLabel l=new JLabel(s);l.setFont(new Font("SansSerif",Font.BOLD,13));l.setBorder(BorderFactory.createEmptyBorder(0,0,6,0));return l;}JButton button(String s,Color c){JButton b=new JButton(s);b.setMaximumSize(new Dimension(500,46));b.setBackground(c);b.setForeground(Color.WHITE);b.setFocusPainted(false);b.setFont(new Font("SansSerif",Font.BOLD,14));return b;}
 void login(){try{Response r=api.call(new Request("login").put("email",email.getText()).put("password",new String(pass.getPassword())));if(r.ok){dispose();new Dashboard((User)r.payload,api).setVisible(true);}else JOptionPane.showMessageDialog(this,r.message,"Sign in",JOptionPane.WARNING_MESSAGE);}catch(Exception e){error(e);}}
 void registerMode(){if(name.getParent()==null){JLabel nl=label("Your name");((JPanel)email.getParent()).add(nl,2);((JPanel)email.getParent()).add(name,3);((JPanel)email.getParent()).revalidate();title.setText("Create your account");}else register();}
 void register(){try{Response r=api.call(new Request("register").put("name",name.getText()).put("email",email.getText()).put("password",new String(pass.getPassword())));if(r.ok){dispose();new Dashboard((User)r.payload,api).setVisible(true);}else JOptionPane.showMessageDialog(this,r.message,"Create account",JOptionPane.WARNING_MESSAGE);}catch(Exception e){error(e);}}
 void error(Exception e){JOptionPane.showMessageDialog(this,e.getMessage(),"Connection error",JOptionPane.ERROR_MESSAGE);}
}
